### PR TITLE
fixed syntax error in catch block

### PR DESCRIPTION
**Pull request by mubarak1988**
updated catch block

### CODE REVIEW

**Comment by walery** [comment]
That was intended and not a mistake.

Since the parameter in JavaScript are optional, I didn't added it, because it's not used. But I was in doubt if this is maybe an error as I saw your PR. For that reason I looked in the [doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch):

> If the catch block does not utilize the exception's value, you can omit the exceptionVar and its surrounding parentheses, as catch {...}.

So it can be left out, but also the parentheses needs to be left out. This is why I'll reject this PR.

Thank you anyway for reviewing - I really appreciate it!

**Comment by mubarak1988** [comment]
This fails on node 16.16 for me. may I suggest then we remove the parentheses in catch as shown in the doc you referred [doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch):

If the catch block does not utilize the exception's value, you can omit the exceptionVar and its surrounding parentheses, as catch {...}. ?

**Comment by walery** [comment]
What is the error message? Is that related to the parentheses?

**Comment by mubarak1988** [comment]
yes related to the parentheses. 
 ```
} catch () {
           ^

SyntaxError: Unexpected token ')'
```

**Comment by walery** [comment]
I'll take a look and release new version once I can reproduce.

**Comment by walery** [comment]
Hmm, I'm not able to reproduce the issue. But I'm using node 19.5.0. Maybe you can increase your node version and give a try?

**Comment by walery** [comment]
I had a thought today in the morning: maybe I can't reproduce is because my code is not jumping into the catch statement and so the catch is never executed and produces the error you see. So I tired it out:

image

This is not the case as you can see. I got the expected error message from the catch block.

**Comment by walery** [comment]
I've used docker image with node 16.16 (the version you're using) to try it out. It worked as well:

image

For reference I'm posting the Docker setup:

<details><summary>serverless.yml</summary>
<p>

```yaml
service: ${self:custom.product}-${self:custom.ccomponent}

frameworkVersion: '>=3.0.0 <4.0.0'

plugins:
  - '@walery/serverless-plugin-stencil'

provider:
  name: aws
  deploymentBucket:
    name: ${stencil(product-bucket):name}
  deploymentPrefix: ${stencil(product-bucket):deploymentPrefix}

custom:
  product: bug
  ccomponent: fix

resources:
  - Resources:
      DummyPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
          ManagedPolicyName: !Sub ${AWS::StackName}-dummy-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: DescribeAccount
                Effect: Allow
                Action:
                  - '*:*'
                Resource:
                  - '*'
```

</p>
</details>

<details><summary>package.json</summary>
<p>

```json
{
  "devDependencies": {
    "@walery/serverless-plugin-stencil": "0.0.4",
    "serverless": "3.22.0"
  }
}
```

</p>
</details>

<details><summary>Dockerfile</summary>
<p>

```Dockerfile
FROM node:16.16

WORKDIR /foo

COPY serverless.yml serverless.yml
COPY package.json package.json

RUN npm install

ENTRYPOINT ["npx", "sls", "package"]
```

</p>
</details>

<details><summary>aws.creds</summary>
<p>

```env
AWS_ACCESS_KEY_ID=...
AWS_SECRET_ACCESS_KEY=...
AWS_SESSION_TOKEN=...
```

</p>
</details>

Build it:

`docker build -t walery/stencil-product-bucket/issue-3 .`

And run it:

`docker run --env-file aws.creds walery/stencil-product-bucket/issue-3:latest`

**Comment by walery** [comment]
@mubarak1988 Maybe you can double-check your setup. In case it still appears, please give some more details so that I can reproduce (and fix the bug).

**Comment by mubarak1988** [comment]
@walery it works fine with this plugin version. @walery/serverless-plugin-stencil": "0.0.4" however, I get that error when I am using the latest 0.0.5 version. I am checking what changed.

**Comment by walery** [comment]
Ah, you're right - I tested it under wrong version. I'll also take an additional look.

**Comment by walery** [comment]
Okay, I can reproduce it with version 0.0.5. I'll take deeper look over the next days.

image

**Comment by walery** [comment]
@mubarak1988 New version is released that fixes the issues:

https://github.com/walery/serverless-plugin-stencil/releases/tag/v0.0.6

Thanks for reporting!

**Comment by mubarak1988** [comment]
Great! Thank you as well @walery !

**Pull request closed without merging**
